control:

  hold_time: 5
  sequence_step: 0.5

  distance:
    kp: 2.0
    ki: 0.0
    kd: 0.0
    lim_low: -2
    lim_high: 2

  distance_vel:
    kp: 0.1
    ki: 0.0
    kd: 0.0
    lim_low: -0.15
    lim_high: 0.15  