joy:
  axis_linear:
    x: 3
    y: 2
    z: 1
  
  axis_angular:
    yaw: 0

  scale_attitude:
    x: 0.1
    y: 0.1
    z: 75
    yaw: 25
  
  scale_position:
    x: 0.05
    y: 0.05
    z: 0.1
    yaw: 25

  detection_state: 5
  left_seq: 0
  right_seq: 2