control:

  rate: 50
  sim_mode: false
  hover: 0.47
  carrot_tol: 0.15

  pitch:  
    kp: 1.0
    ki: 0.0
    kd: 0.0
    lim_low: -2.0
    lim_high: 2.0
  
  pitch_rate:
    kp: 0.1
    ki: 0.0
    kd: 0.0
    lim_low: -0.4
    lim_high: 0.4  

  pos_y:
    kp: 1.0
    ki: 0.0
    kd: 0.0
    lim_low: -2.0
    lim_high: 2.0
   
  vel_y:
    kp: 0.1
    ki: 0.0
    kd: 0.0
    lim_low: -0.4
    lim_high: 0.4 

  pos_z:
    kp: 1.5
    ki: 0.1
    kd: 0.0
    lim_low: -2
    lim_high: 2

  vel_z:
    kp: 0.4
    ki: 0.0
    kd: 0.0
    lim_low: -0.5
    lim_high: 0.5  
