control:

  rate: 20
  sim_mode: true
  hover: 0.3

  pitch:
    kp: 2.0
    ki: 0.0
    kd: 0.0
    lim_low: -2
    lim_high: 2
  
  pitch_rate:
    kp: 0.1
    ki: 0.0
    kd: 0.0
    lim_low: -0.15
    lim_high: 0.15  

  pos_y:
    kp: 2.0
    ki: 0.0
    kd: 0.0
    lim_low: -2
    lim_high: 2
   
  vel_y:
    kp: 0.1
    ki: 0.0
    kd: 0.0
    lim_low: -0.15
    lim_high: 0.15

  pos_z:
    kp: 15
    ki: 3.0
    kd: 5.0
    lim_low: -50
    lim_high: 50

  vel_z:
    kp: 0.1
    ki: 0.0
    kd: 0.0
    lim_low:  0
    lim_high: 1    
