control:

  rate: 50
  sim_mode: false
  hover: 0.3

  pitch:
    kp: 2.0
    ki: 0.0
    kd: 0.0
    lim_low: -2.0
    lim_high: 2.0
  
  pitch_rate:
    kp: 0.1
    ki: 0.0
    kd: 0.0
    lim_low: -0.4
    lim_high: 0.4  

  pos_y:
    kp: 2.0
    ki: 0.0
    kd: 0.0
    lim_low: -2.0
    lim_high: 2.0
   
  vel_y:
    kp: 0.1
    ki: 0.0
    kd: 0.0
    lim_low: -0.4
    lim_high: 0.4 

  pos_z:
    kp: 0.1
    ki: 0.0
    kd: 0.0
    lim_low: -0.15
    lim_high: 0.15

  vel_z:
    kp: 0.1
    ki: 0.0
    kd: 0.0
    lim_low: -0.15
    lim_high: 0.15  
