pursuit:
  state_machine:
    
    rate: 50
    uav_distance_offset: 0.0
    ball_distance_offset: 5.0
    z_offset: 0.0

    search:
      desired_height: 10.0
      x_size: 100.0
      y_size: 40.0
      x_offset: 0.0
      y_offset: 0.0
      x_takeOff: 0.0
      y_takeOff: 0.0