visual_servo:
  state_machine:
    
    rate: 50
    min_error: 0.5
    min_touchdown_target_position_error_xy: 0.03
    min_touchdown_target_position_error_z: 0.05
    min_touchdown_uav_velocity_error_xy: 0.05
    min_touchdown_uav_velocity_error_z: 0.05
    min_touchdown_align_duration: 5
    min_yaw_error: 0.05
    touchdown_height: 1.5
    magnet_offset: 0.25
    touchdown_speed: 1
    after_touchdown_height: 4
    descent_speed: 0.2
    ascent_speed: 1
    detection_counter: 25
