\visual_servo:
  state_machine:
    
    rate: 50
    min_error: 0.1
    min_yaw_error: 0.05
    touchdown_height: 0.8
    touchdown_delta: 0.6
    touchdown_duration: 2
    after_touchdown_height: 3.1
    descent_speed: 0.1
    ascent_speed: 0.5
    detection_counter: 25

    offset_x_1: 0.03
    offset_x_2: 0.03

    offset_y_1: -0.2
    offset_y_2: -0.075
