visual_servo:
  state_machine:
    
    rate: 50
    min_error: 0.5
    min_touchdown_target_position_error: 0.1
    min_touchdown_uav_velocity_error: 0.3
    min_yaw_error: 0.05
    touchdown_height: 1
    magnet_offset: 0.2
    touchdown_speed: 1
    after_touchdown_height: 3.1
    descent_speed: 0.2
    ascent_speed: 0.5
    detection_counter: 150