pursuit:
  state_machine:
    
    rate: 50
    uav_distance_offset: 7.0
    ball_distance_offset: 5.0
    z_offset: 0.0
    yaw_deadzone: 0.0
    settle_threshold: 0.2
    gps_num_points: 5
    collect_timeout: 90.0
    after_takeoff_height : 10.0

    search:
      desired_height: 10.0
      x_size: 5.0
      y_size: 1.0
      x_offset: 0.0
      y_offset: 0.0
      yaw_offset: 0.0
      x_takeOff: 0.0
      y_takeOff: 0.0

    interception:
      z_offset: -3.0

    gps_land:
      lat:
        24.417669
      lon:
        54.4359772
      height:
        7.0

  gps_points:
    '1':
      lat:
        24.4177322
      lon:
        54.4357988
      alt:
        10.0
      hdg:
        4.36332313
    '2':
      lat:
        24.4178097
      lon:
        54.43568
      alt:
        10.0
      hdg:
        4.9741883682
    '3':
      lat:
        24.4177399
      lon:
        54.4357013
      alt:
        10.0
      hdg:
        4.799655443
    '4':
      lat:
        24.4176738
      lon:
        54.4361611
      alt:
        10.0
      hdg:
        4.1015237422
    '5':
      lat:
        24.4176927
      lon:
        54.4361601
      alt:
        10.0
      hdg:
        3.926990817