visual_servo:
  state_machine:
    
    rate: 50
    min_error: 0.04
    min_yaw_error: 0.05
    touchdown_height: 0.6
    touchdown_delta: 0.6
    touchdown_duration: 1.75
    after_touchdown_height: 3.1
    descent_speed: 0.1
    ascent_speed: 0.4
    detection_counter: 200

    offset_x_1: 0
    offset_x_2: 0

    offset_y_1: 0.2
    offset_y_2: 0.1