visual_servo:
  state_machine:
    
    rate: 50
    min_error: 0.1
    min_touchdown_target_position_error_xy: 0.2
    min_touchdown_target_position_error_z: 1
    min_touchdown_uav_velocity_error_xy: 1
    min_touchdown_uav_velocity_error_z: 1
    min_touchdown_align_duration: 0
    min_yaw_error: 0.025
    touchdown_height: 1
    magnet_offset: -0.1
    touchdown_speed: 0.8
    after_touchdown_height: 2
    descent_speed: 0.15
    ascent_speed: 0.5
    detection_counter: 25
