visual_servo:
  
  camera_fov: 90
  compensate_roll_and_pitch: false
  yaw_added_offset: 0.0
  filter_k: 0.05

  pid_x:
    x_armed:  false
    kp:  0.1
    ki:  0
    kd:  0
    lim_low: -0.75
    lim_high: 0.75
    deadzone_x: 0 

  pid_y:
    y_armed:  true
    kp:  0.4
    ki:  0
    kd:  0
    lim_low: -0.5
    lim_high: 0.5
    deadzone_y: 0

  pid_z:  
    z_armed: true
    kp:  1.0
    ki:  0
    kd:  0  
    lim_low: -1.0
    lim_high: 1.0
    deadzone_z: 0

  pid_yaw:
    yaw_armed: true
    kp:  0.2
    ki:  0.005
    kd:  0
    lim_low: -0.5
    lim_high: 0.5
    deadzone_yaw: 0
