!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  deadzone_dist: 0.02
  deadzone_x: 0.01
  deadzone_y: 0.01
  deadzone_yaw: 0.02
  deadzone_z: 0.5
  dist_armed: false
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        dictitems:
          Distance_control: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              deadzone_dist: 0.02
              dist_armed: false
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 5
              k_d_dist: 0.0
              k_i_dist: 0.0
              k_p_dist: 0.0
              name: Distance_control
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              saturation_dist: 2.0
              state: true
              type: ''
            state: []
          General_parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 6
              is_bricklaying: true
              landing_speed: 0.2
              name: General_parameters
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              pickup_allowed: false
              shutdown_height: 0.6
              state: true
              type: ''
              use_odometry: true
              yaw_difference: 0.0
            state: []
          X_axis: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              deadzone_x: 0.01
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 1
              k_d_x: 0.0
              k_i_x: 0.0
              k_p_x: 0.5
              landing_range_x: 0.05
              name: X_axis
              offset_x_1: 0.0
              offset_x_2: 0.0
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              saturation_x: 2.0
              state: true
              type: ''
              x_armed: true
            state: []
          Y_axis: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              deadzone_y: 0.01
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 2
              k_d_y: 0.0
              k_i_y: 0.0
              k_p_y: 0.5
              landing_range_y: 0.05
              name: Y_axis
              offset_y_1: -0.4
              offset_y_2: -0.25
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              saturation_y: 2.0
              state: true
              type: ''
              y_armed: true
            state: []
          Yaw_control: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              deadzone_yaw: 0.02
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 4
              k_d_yaw: 0.0
              k_i_yaw: 0.07
              k_p_yaw: 0.0
              landing_range_yaw: 0.05
              name: Yaw_control
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              saturation_yaw: 2.0
              state: true
              type: ''
              yaw_armed: true
            state: []
          Z_axis: !!python/object/new:dynamic_reconfigure.encoding.Config
            dictitems:
              deadzone_z: 0.5
              groups: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              id: 3
              k_d_z: 0.0
              k_i_z: 0.0
              k_p_z: 0.0
              landing_range_z: 0.05
              name: Z_axis
              parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
                state: []
              parent: 0
              saturation_z: 2.0
              state: true
              type: ''
              z_armed: false
            state: []
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
    state: []
  is_bricklaying: true
  k_d_dist: 0.0
  k_d_x: 0.0
  k_d_y: 0.0
  k_d_yaw: 0.0
  k_d_z: 0.0
  k_i_dist: 0.0
  k_i_x: 0.0
  k_i_y: 0.0
  k_i_yaw: 0.07
  k_i_z: 0.0
  k_p_dist: 0.0
  k_p_x: 0.5
  k_p_y: 0.5
  k_p_yaw: 0.0
  k_p_z: 0.0
  landing_range_x: 0.05
  landing_range_y: 0.05
  landing_range_yaw: 0.05
  landing_range_z: 0.05
  landing_speed: 0.2
  offset_x_1: 0.0
  offset_x_2: 0.0
  offset_y_1: -0.4
  offset_y_2: -0.25
  pickup_allowed: false
  saturation_dist: 2.0
  saturation_x: 2.0
  saturation_y: 2.0
  saturation_yaw: 2.0
  saturation_z: 2.0
  shutdown_height: 0.6
  use_odometry: true
  x_armed: true
  y_armed: true
  yaw_armed: true
  yaw_difference: 0.0
  z_armed: false
state: []
