pursuit:
  state_machine:
    
    rate: 50
    uav_distance_offset: 0.0
    ball_distance_offset: 5.0
    z_offset: 0.0

    search:
      desired_height: 5.0
      x_size: 100.0
      y_size: 60.0
      x_offset: 0.0
      y_offset: 0.0
      yaw_offset: 0.0
      uav_yaw: 0.0
      x_takeOff: -50.0
      y_takeOff: -30.0
