visual_servo:
  
  camera_h_fov: 40
  camera_v_fov: 30
  compensate_roll_and_pitch: false
  compensate_camera_nonlinearity: false
  yaw_added_offset: -1.57

  pid_x:
    x_armed:  true
    kp:  0.75
    ki:  0
    kd:  0
    lim_low: -0.75
    lim_high: 0.75
    deadzone_x: 0

  pid_y:
    y_armed:  true
    kp:  0.75
    ki:  0
    kd:  0
    lim_low: -0.75
    lim_high: 0.75
    deadzone_y: 0

  pid_z:  
    z_armed: false
    kp:  0
    ki:  0
    kd:  0  
    lim_low: -0.5
    lim_high: 0.5
    deadzone_z: 0

  pid_yaw:
    yaw_armed: true
    kp:  0.2
    ki:  0.01
    kd:  0
    lim_low: -0.05
    lim_high: 0.05
    deadzone_yaw: 0
