visual_servo:
  
  camera_fov: 80
  compensate_roll_and_pitch: true

  pid_x:
    x_armed:  true
    kp:  1
    ki:  0.1
    kd:  0
    lim_low: -0.5
    lim_high: 0.5
    deadzone_x: 0

  pid_y:
    y_armed:  true
    kp:  1
    ki:  0.1
    kd:  0
    lim_low: -0.5
    lim_high: 0.5
    deadzone_y: 0

  pid_z:  
    z_armed: false
    kp:  0
    ki:  0
    kd:  0  
    lim_low: -0.5
    lim_high: 0.5
    deadzone_z: 0

  pid_yaw:
    yaw_armed: true
    kp:  0.2
    ki:  0.01
    kd:  0
    lim_low: -0.05
    lim_high: 0.05
    deadzone_yaw: 0